USE ismapper;

CREATE TABLE cancerTumours
(
	id int(99) NOT NULL,
	abbreviation text NOT NULL,
	term text NOT NULL,
	mutation text NOT NULL,
	genes text NOT NULL,
	PRIMARY KEY(id)
);

INSERT INTO cancerTumours (id,abbreviation,term,mutation,genes) VALUES
(0, "AML", "acute myeloid leukaemia", "Somatic, Germline", "ABI1;ABL2;ACSL6;ARHGAP26;ARHGEF12;ARNT;BCOR;BCR;BRIP1;CASC5;CBFA2T3;CBFB;CBL;CBLB;CBLC;CDX2;CEBPA;CHIC2;CLP1;CREBBP;CUX1;DEK;DNMT3A;ELF4;EP300;ERG;FANCA;FANCC;FANCD2;FANCE;FANCF;FANCG;FLT3;FNBP1;FUS;GMPS;HOXA13;HOXC11;HOXC13;HOXD11;JAK2;KAT6A;KAT6B;KDM5A;KIT;KMT2A;KRAS;LASP1;MECOM;MLF1;MN1;MNX1;MYH11;NCOA2;NPM1;NRAS;NSD1;NUP214;NUP98;PDGFRB;PER1;PICALM;PRDM16;PRRX1;PSIP1;PTPN11;RAD21;RPL22;RPN1;RUNX1;RUNX1T1;SBDS;sep-05;sep-06;SET;TET1;TRIP11;WHSC1L1"),
(2, "CML", "chronic myeloid leukaemia", "Somatic", "ABL1;BCR;CCDC6;HOXA11;MECOM;MSI2;PCM1;PDGFRB;RPL22"),
(3, "ALL", "acute lymphocytic leukaemia", "Somatic", "ABL1;AFF3;AFF4;BCR;CDK6;CREBBP;EP300;EPS15;EWSR1;FCGR2B;FLT3;FOXP1;HLF;IKZF1;IL7R;JAK1;JAK2;KMT2A;MLLT11;MLLT3;NCKIPSD;PAX5;PML;RANBP17;TAF15;TTL;ZNF384;ZNF521"),
(4, "T-ALL", "T-cell acute lymphoblastic leukaemia", "Somatic", "ABL1;AFF3;BCL11B;CNOT3;DNM2;FBXW7;KDM6A;LCK;LMO1;LMO2;LYL1;NOTCH1;NUP214;OLIG2;PICALM;PTPRC;RAP1GDS1;RPL10;RPL5;RUNX1;STIL;TAL2;TCL6;TLX1;TLX3;TRA;TRB"),
(5, "", "lipoma", "Somatic", "ACKR3;C12orf9;EBF1;HMGA2;LHFP;LPP;NFIB;RAD51B"),
(6, "", "prostate", "Somatic, Germline", "ACSL3;AXIN1;BRAF;CANT1;DDX5;ELK4;ERG;ETV1;ETV5;FOXA1;HERPUD1;HMGN2P46;HNRNPA2B1;KLF6;KLK2;NDRG1;PTEN;PTEN;RAF1;SLC45A3;SPOP;TMPRSS2"),
(7, "AEL", "acute eosinophilic leukaemia", "Somatic", "ACSL6"),
(8, "DIPG", "diffuse intrinsic pontine glioma", "Somatic", "ACVR1"),
(9, "AL", "acute leukaemia", "Somatic", "AFF1;ELL;FOXO3;FOXO4;GPHN;MLLT1;MLLT10;MLLT4;MLLT6;SH3GL1"),
(10, "", "papillary thyroid", "Somatic, Germline", "AKAP9;BRAF;CCDC6;ERC1;GOLGA5;HOOK3;KTN1;NCOA4;NTRK1;PCM1;PRKAR1A;PRKAR1A;RET;STRN;TFG;TPM3;TPR;TRIM27;TRIM33"),
(11, "", "breast", "Somatic, Germline", "AKT1;ARID1A;ARID1B;BAP1;BRCA1;BRCA2;BRCA2;BRIP1;CASP8;CCND1;CDKN1B;CHEK2;EP300;ERBB2;ESR1;FOXA1;GATA3;MAP2K4;MAP3K13;NCOR1;NOTCH1;PALB2;PBRM1;PIK3CA;RB1;RB1;SMARCD1;TBX3;TP53;TP53"),
(12, "", "colorectal", "Somatic, Germline", "AKT1;APC;APC;AXIN1;BRAF;C2orf44;CTNNB1;CUX1;EIF3E;EP300;FBXW7;KRAS;MAP2K1;MAP2K4;MDM2;MLH1;MLH1;MSH2;MSH2;MSH6;MSH6;MUTYH;PIK3CA;PIK3R1;PMS1;PMS2;PTPRK;RAD21;RSPO2;RSPO3;SMAD4;TCF7L2;TP53;UBR5;VTI1A"),
(13, "", "ovarian", "Somatic, Germline", "AKT1;AKT2;BRCA1;BRCA1;BRCA2;BRCA2;CTNNB1;ERBB2;MLH1;MLH1;MSH2;MSH2;MSH6;PIK3R1;PMS1;PMS2;STK11"),
(14, "NSCLC", "non small cell lung cancer", "Somatic, Germline", "AKT1;ALK;BAP1;BRAF;CCDC6;CD74;EGFR;EGFR;EML4;ERBB2;EZR;FGFR2;HIP1;KDR;KIF5B;LRIG3;MAP2K1;MAP2K2;NFE2L2;NKX2-1;NRG1;RET;ROS1;SDC4;SLC34A2;SMARCA4;SOX2;STK11;TFG;TPM3;TPR"),
(15, "", "pancreatic", "Somatic, Germline", "AKT2;APC;APC;BRCA2;BRCA2;CDKN2A;CDKN2a(p14);EP300;KRAS;MAP2K4;SMAD4;STK11;STK11"),
(16, "", "leiomyoma", "Somatic", "ALDH2;CCNB1IP1;HMGA2"),
(17, "ALCL", "anaplastic large-cell lymphoma", "Somatic", "ALK;ATIC;CARS;CLTC;CLTCL1;MSN;MYH9;RNF213;TFG;TPM3;TPM4"),
(18, "", "neuroblastoma", "Somatic, Germline", "ALK;ALK;LMO1;LMO1;MYCN;PHOX2B;PHOX2B"),
(19, "", "inflammatory myofibroblastic tumour", "Somatic", "ALK;DCTN1;PPFIBP1;RANBP2"),
(20, "", "Spitzoid tumour", "Somatic", "ALK;BRAF;CEP89;CLIP1;DCTN1;ERC1;GOLGA5;HLA-A;KIAA1598;KIF5B;LMNA;LSM14A;MYO5A;NTRK1;PPFIBP1;PWWP2A;RET;ROS1;TP53;TPM3;ZCCHC8"),
(21, "", "Wilms tumour", "Somatic, Germline", "AMER1;DICER1;GPC3;PALB2;WT1;WT1"),
(22, "", "desmoid", "Somatic, Germline", "APC;APC"),
(23, "", "hepatoblastoma", "Somatic, Germline", "APC;APC;AXIN1"),
(24, "", "glioma", "Somatic, Germline", "APC;APC;ATM;CDKN2C;EGFR;H3F3A;HIST1H3B;KLF6;MDM2;NBN;NF1;NF1;PMS2;PTEN;PTEN;TP53;TP53"),
(25, "", "other CNS", "Somatic, Germline", "APC;APC"),
(26, "MDS", "myelodysplastic syndrome", "Somatic, Germline", "ARHGAP26;ASXL1;CALR;CBL;CEBPA;CSF3R;CUX1;ETV6;MDS2;MECOM;PRDM16;PTPN11;SBDS;SRSF2;SYK;TET2;U2AF1;ZRSR2"),
(27, "", "clear cell ovarian carcinoma", "Somatic", "ARID1A;PPP2R1A"),
(28, "RCC", "renal cell carcinoma", "Somatic", "ARID1A;BAP1"),
(29, "", "hepatocellular carcinoma", "Somatic, Germline", "ARID1B;ARID2;AXIN1;AXIN2;HNF1A;IL6ST;TERT"),
(30, "", "alveolar soft part sarcoma", "Somatic", "ASPSCR1;TFE3"),
(31, "CMML", "chronic myelomonocytic leukaemia", "Somatic", "ASXL1;CSF3R;ETNK1;HIP1;PDGFRB;PER1;RABEP1;SETBP1"),
(32, "", "malignant melanoma of soft parts", "Somatic", "ATF1"),
(33, "", "angiomatoid fibrous histiocytoma", "Somatic", "ATF1;CREB1;FUS"),
(34, "T-PLL", "T-cell prolymphocytic leukaemia", "Somatic", "ATM"),
(35, "", "leukaemia", "Somatic, Germline", "ATM;BLM;BRIP1;FANCA;FANCC;FANCD2;FANCE;FANCF;FANCG;LPP"),
(36, "", "lymphoma", "Germline", "ATM;BLM;PRF1;WAS"),
(37, "", "medulloblastoma", "Somatic, Germline", "ATM;KDM6A;KMT2C;KMT2D;NBN;PALB2;PMS2;PTCH1;PTCH1;SUFU;SUFU;TERT"),
(38, "", "adrenal aldosterone producing adenoma", "Somatic", "ATP1A1;ATP2B3;CACNA1D"),
(39, "", "endometrial", "Somatic, Germline", "ATR;AXIN1;CUX1;FBXW7;FGFR2;MLH1;MLH1;MSH2;MSH2;MSH6;PMS1;PMS2;PTEN;PTEN"),
(40, "", "gastric", "Somatic, Germline", "ATR;BRAF;CDH1;CDH1;ERBB2;ERBB3;FGFR2;PIK3CA;UBR5"),
(41, "", "oropharyngeal", "Germline", "ATR"),
(42, "", "pancreatic neuroendocrine tumours", "Somatic", "ATRX"),
(43, "", "paediatric GBM", "Somatic", "ATRX"),
(44, "", "sporadic medulloblastoma", "Somatic", "AXIN1"),
(45, "", "colorectal carcinoma", "Somatic, Germline", "AXIN2;AXIN2;POLE;TBL1XR1"),
(46, "", "stomach carcinoma", "Somatic", "AXIN2;POLE"),
(47, "", "uveal melanoma", "Somatic, Germline", "BAP1;BAP1;GNA11;GNAQ"),
(48, "", "mesothelioma", "Somatic, Germline", "BAP1;EWSR1;TERT"),
(49, "MALT", "mucosa-associated lymphoid tissue lymphoma", "Somatic", "BCL10;BIRC3;IGH;MALT1"),
(50, "B-CLL", "B-cell lymphocytic leukaemia", "Somatic", "BCL11A;BTG1;FSTL3;MYC"),
(51, "NHL", "non-Hodgkin lymphoma", "Somatic, Germline", "BCL2;BCL6;CCND2;CNTRL;EIF4A2;FGFR1;FGFR1OP;HIST1H4I;HSP90AA1;HSP90AB1;IGH;IL21R;LCP1;NACA;NBN;NPM1;PAX5;PIM1;POU2AF1;RHOH;TFRC;ZNF198"),
(52, "CLL", "chronic lymphocytic leukaemia", "Somatic", "BCL2;BCL3;BCL5;BCL6;BIRC3;CCND1;CCND2;IGH;NFKBIE;POT1;SRSF2;U2AF1;XPO1;ZRSR2"),
(53, "", "BNHL", "Somatic", "BCL7A"),
(54, "B-ALL", "B-cell acute lymphocytic leukaemia", "Somatic", "BCL9;CCND1;CRLF2;CRLF2;ELN;IGH;P2RY8;P2RY8;PAX5;RNF217-AS1;SH2B3"),
(55, "", "retinoblastoma", "Somatic, Germline", "BCOR;MDM4;RB1;RB1"),
(56, "", "APL (translocation)", "Somatic", "BCOR"),
(57, "MCL", "mantle cell lymphoma", "Somatic", "BIRC3"),
(58, "MM", "multiple myeloma", "Somatic", "BIRC3;CCND3;CDKN2C;FAM46C;FGFR3;IGH;IRF4;KDM6A;MAF;MAFB;NRAS;WHSC1"),
(59, "", "skin squamous cell", "Somatic, Germline", "BLM;DDB2;ERCC2;ERCC3;ERCC4;ERCC5;TERT;XPA;XPC"),
(60, "", "other tumour types", "Somatic, Germline", "BLM;CTNNB1;CUX1;DICER1;ERBB2;KDM6A;KRAS;MDM2;TERT;WRN"),
(61, "", "gastrointestinal polyps", "Germline", "BMPR1A"),
(62, "", "melanoma", "Somatic, Germline", "BRAF;CDK4;CDKN2A;CDKN2A;CDKN2a(p14);CDKN2a(p14);CUX1;DDB2;ERCC2;ERCC3;ERCC4;ERCC5;GRIN2A;MAP2K1;MAP2K2;MITF;NRAS;PPP6C;RAC1;STAG2;TERT;TERT;TRRAP;XPA;XPC"),
(63, "", "borderline ovarian", "Somatic", "BRAF"),
(64, "", "cholangiocarcinoma", "Somatic", "BRAF;RNF43"),
(65, "", "pilocytic astrocytoma", "Somatic", "BRAF;FAM131B;KIAA1549;RAF1;SRGAP3"),
(66, "", "pancreas acinar carcinoma", "Somatic", "BRAF;SND1"),
(67, "", "melanocytic nevus", "Somatic", "BRAF"),
(68, "", "leukaemia  (FANCB", "Germline", "BRCA2"),
(69, "", "FANCD1)", "Germline", "BRCA2"),
(70, "", "lethal midline carcinoma of young people", "Somatic", "BRD3;BRD4"),
(71, "", "rhabdomyosarcoma", "Somatic, Germline", "BUB1B;FGFR4;HRAS;NBN;NCOA2"),
(72, "PMBL", "primary mediastinal B-cell lymphoma", "Somatic", "C15orf65;CD274;CIITA;PDCD1LG2;RALGDS;RMI2;RUNDC2A;SOCS1;TNFAIP3"),
(73, "", "Hodgkin lymphoma", "Somatic", "C15orf65;CD274;CIITA;PDCD1LG2;RALGDS;REL;RMI2;RUNDC2A;SOCS1;TNFAIP3"),
(74, "MPN", "myeloproliferative neoplasm", "Somatic, Germline", "CALR;CNTRL;FGFR1;FGFR1OP;JAK2;MPL;MPL;NIN;PCM1;PDE4DIP;PDGFRB;SH2B3;ZNF198"),
(75, "", "epithelioid haemangioendothelioma", "Somatic", "CAMTA1;WWTR1"),
(76, "DLBCL", "diffuse large B-cell lymphoma", "Somatic", "CARD11;CD79A;CD79B;CREBBP;EP300;EZH2;FBXO11;IKZF1;NOTCH2;PRDM1;SPEN"),
(77, "", "hepatocellular", "Somatic", "CASP8;HNF1A"),
(78, "", "oral squamous cell", "Somatic", "CASP8"),
(79, "JMML", "juvenile myelomonocytic leukaemia", "Somatic", "CBL;PTPN11;SETBP1;SPECC1"),
(80, "", "serous ovarian", "Somatic", "CCNE1;CDK12"),
(81, "WM", "Waldenstrom's macroglobulinaemia", "Somatic", "CD79A;CD79B"),
(82, "", "parathyroid adenoma", "Somatic, Germline", "CDC73;CDC73;MEN1"),
(83, "", "multiple ossifying jaw fibroma", "Germline", "CDC73"),
(84, "", "lobular breast", "Somatic", "CDH1"),
(85, "", "aneurysmal bone cyst", "Somatic", "CDH11;CNBP;COL1A1;OMD;THRAP3;USP6"),
(86, "", "small intestine neuroendocrine tumours", "Somatic", "CDKN1B"),
(87, "", "pituitary", "Germline", "CDKN1B"),
(88, "", "parathyroid", "Germline", "CDKN1B"),
(89, "", "multiple other tumour types", "Somatic, Germline", "CDKN2A;CDKN2a(p14);TP53;TP53"),
(90, "", "salivary adenoma", "Somatic", "CHCHD7;FGFR1;LIFR;PLAG1;TCEA1"),
(91, "", "extraskeletal myxoid chondrosarcoma", "Somatic", "CHN1;NR4A3;TAF15;TCF12;TFG"),
(92, "", "oligodendroglioma", "Somatic", "CIC;FUBP1"),
(93, "", "soft tissue sarcoma", "Somatic", "CIC;DUX4L1;FLT4;FOXO4"),
(94, "", "renal", "Somatic, Germline", "CLTC;FH;FLCN;KDM6A;KMT2D;NF2;TFE3;VHL;VHL"),
(95, "DFSP", "dermatofibrosarcoma protuberans", "Somatic", "COL1A1;PDGFB"),
(96, "", "chondrosarcoma", "Somatic", "COL2A1;NCOA2"),
(97, "", "enchondroma", "Somatic", "COL2A1"),
(98, "", "uterine leiomyoma", "Somatic", "COX6C;MED12;RAD51B"),
(99, "", "clear cell sarcoma", "Somatic", "CREB1;EWSR1"),
(100, "", "myxofibrosarcoma", "Somatic", "CREB3L1"),
(101, "", "fibromyxoid sarcoma", "Somatic", "CREB3L2;FUS"),
(102, "B-NHL", "B-cell non-Hodgkin lymphoma", "Somatic", "CREBBP;DDX6;FCRL4;IGK;KDSR;MUC1;NFKB2"),
(103, "", "Downs associated ALL", "Somatic", "CRLF2;CRLF2"),
(104, "", "salivary gland mucoepidermoid", "Somatic", "CRTC1;CRTC3;MAML2"),
(105, "aCML", "atypical chronic myeloid leukaemia", "Somatic", "CSF3R;ETNK1;SETBP1"),
(106, "CNL", "chronic neutrophilic leukaemia", "Somatic", "CSF3R"),
(107, "", " leukaemia lymphoma and MDS associated with severe congenital neutropenia", "Somatic", "CSF3R"),
(108, "", "de novo AML", "Somatic", "CSF3R"),
(109, "", " hepatoblastoma", "Somatic", "CTNNB1"),
(110, "", "pleomorphic salivary gland adenoma", "Somatic", "CTNNB1;FHIT;HMGA2;WIF1"),
(111, "", "cylindroma", "Somatic, Germline", "CYLD;CYLD"),
(112, "", "pancreatic neuroendocrine tumour", "Somatic", "DAXX;MEN1"),
(113, "", "paediatric glioblastoma", "Somatic", "DAXX;PDGFRA"),
(114, "", "skin basal cell", "Somatic, Germline", "DDB2;ERCC2;ERCC3;ERCC4;ERCC5;PTCH1;PTCH1;RECQL4;SMO;STAT5B;TERT;XPA;XPC"),
(115, "", "liposarcoma", "Somatic", "DDIT3;FUS"),
(116, "AML*", "acute myeloid leukaemia (primarily treatment associated)", "Somatic", "DDX10;GAS7;HOXA9;HOXD13;sep-09;TOP1"),
(117, "", "sex cord-stromal tumour", "Somatic", "DICER1"),
(118, "TGCT", "testicular germ cell tumour", "Somatic", "DICER1;FAS;KIT"),
(119, "", "embryonal rhabdomyosarcoma", "Somatic", "DICER1;MYOD1"),
(120, "", "pleuropulmonary blastoma", "Somatic, Germline", "DICER1;DICER1"),
(121, "", "pituitary blastoma", "Somatic", "DICER1"),
(122, "", "thyroid cancer", "Somatic", "DICER1"),
(123, "", "ETP ALL", "Somatic", "ECT2L;IL7R;JAK3;PHF6"),
(124, "", "colon", "Somatic", "ERBB3"),
(125, "", "head and neck", "Somatic", "ERBB3"),
(126, "", "bladder", "Somatic, Germline", "ERBB3;FGFR3;HRAS;MDM4;NOTCH1;NOTCH2;TERT"),
(127, "", "skin", "Somatic", "ERBB3"),
(128, "", "Ewing sarcoma", "Somatic", "ERG;ETV1;ETV4;EWSR1;FEV;FLI1;FUS;NFATC2;ZNF278"),
(129, "SM-AHD", "systemic mastocytosis associated with other haematological disorder", "Somatic", "ETNK1"),
(130, "HES", "hypereosinophilic syndrome", "Somatic", "ETNK1"),
(131, "", "prostate carcinoma", "Somatic", "ETV4"),
(132, "", "congenital fibrosarcoma", "Somatic", "ETV6;NTRK3"),
(133, "", "multiple different leukaemia and lymphoma tumour types including ALL", "Somatic", "ETV6"),
(134, "", "secretory breast", "Somatic", "ETV6;NTRK3"),
(135, "", "desmoplastic small round cell tumour ", "Somatic", "EWSR1"),
(136, "", "sarcoma", "Somatic, Germline", "EWSR1;JUN;MDM2;POU5F1;RB1;RB1;TP53;TP53"),
(137, "", "myoepithelioma", "Somatic", "EWSR1;PBX1"),
(138, "", "exostoses", "Germline", "EXT1;EXT2"),
(139, "", "osteosarcoma", "Germline", "EXT1;EXT2;RECQL4;WRN"),
(140, "", "nasal NK/T lymphoma", "Somatic", "FAS"),
(141, "", "skin squamous cell carcinoma-burn scar related", "Somatic", "FAS"),
(142, "", "T-cell lymphoma", "Somatic", "FGFR3"),
(143, "", "leiomyomatosis", "Germline", "FH"),
(144, "", "idiopathic hypereosinophilic syndrome", "Somatic", "FIP1L1;PDGFRA"),
(145, "", "fibrofolliculomas", "Germline", "FLCN"),
(146, "", "trichodiscomas", "Germline", "FLCN"),
(147, "", "granulosa-cell tumour of the ovary", "Somatic", "FOXL2"),
(148, "", "alveolar rhabdomyosarcoma", "Somatic", "FOXO1;NCOA1;PAX3;PAX7"),
(149, "", "megakaryoblastic leukaemia of Downs syndrome", "Somatic", "GATA1"),
(150, "", "AML (CML blast transformation)", "Somatic", "GATA2"),
(151, "", "pituitary adenoma", "Somatic, Germline", "GNAS;MEN1"),
(152, "", "glioblastoma", "Somatic", "GOPC;IDH1;IDH2;MDM4;PIK3CA;PIK3R1;ROS1;STAG2;TERT"),
(153, "", "chondroblastoma", "Somatic", "H3F3B"),
(154, "", "mesenchymal chondrosarcoma", "Somatic", "HEY1"),
(155, "", "microfollicular thyroid adenoma", "Somatic", "HMGA1"),
(156, "", "various benign mesenchymal tumours", "Somatic", "HMGA1"),
(157, "", "hepatic adenoma", "Somatic, Germline", "HNF1A;HNF1A"),
(158, "", "infrequent sarcomas", "Somatic", "HRAS"),
(159, "", "rare other tumour types", "Somatic", "HRAS"),
(160, "", "ganglioneuroblastoma", "Germline", "HRAS"),
(161, "", "Burkitt lymphoma", "Somatic", "IGH;IGK;IGL;MYC"),
(162, "MLCLS", "mediastinal large cell lymphoma with sclerosis", "Somatic", "IGH;PAFAH1B2;PCSK7"),
(163, "SMZL", "splenic marginal zone lymphoma", "Somatic", "IKBKB;SPEN"),
(164, "", "intestinal T-cell lymphoma", "Somatic", "IL2;TNFRSF17"),
(165, "", "peripheral T-cell lymphoma", "Somatic", "ITK;SYK"),
(166, "", " CML", "Somatic", "JAK2"),
(167, "", "acute megakaryocytic leukaemia", "Somatic", "JAK3;MKL1;RBM15"),
(168, "", "endometrial stromal tumour", "Somatic", "JAZF1;SUZ12"),
(169, "", "adrenal adenoma", "Somatic", "KCNJ5"),
(170, "", "clear cell renal carcinoma", "Somatic", "KDM5C;PBRM1;SETD2"),
(171, "", "oesophageal SCC", "Somatic", "KDM6A"),
(172, "", "angiosarcoma", "Somatic", "KDR;PLCG1;PTPRB"),
(173, "GIST", "gastrointestinal stromal tumour", "Somatic, Germline", "KIT;KIT;PDGFRA;PDGFRA"),
(174, "", "mastocytosis", "Somatic", "KIT"),
(175, "", "mucosal melanoma", "Somatic", "KIT"),
(176, "", "epithelioma", "Germline", "KIT"),
(177, "", "meningioma", "Somatic, Germline", "KLF4;MN1;NF2;NF2;SMARCE1;TRAF7;WRN"),
(178, "", "lung", "Somatic", "KRAS;MALAT1;RAD21;STRN;TP53"),
(179, "", "thyroid", "Somatic", "KRAS;NRAS"),
(180, "", "renal cell carcinoma (childhood epithelioid)", "Somatic", "MALAT1;TFEB"),
(181, "", "luminal A breast", "Somatic", "MAP3K1"),
(182, "", "pheochromocytoma", "Somatic, Germline", "MAX;MAX;RET;RET;SDHB;SDHC;SDHD;VHL;VHL"),
(183, "", "endometrioid carcinoma", "Somatic", "MAX;POLE"),
(184, "", "colon carcinoma", "Somatic", "MAX"),
(185, "", "parathyroid tumours", "Somatic", "MEN1"),
(186, "", "pancreatic islet cell", "Germline", "MEN1"),
(187, "", "carcinoid", "Germline", "MEN1"),
(188, "", "papillary renal", "Somatic, Germline", "MET;MET;NONO;PRCC;SFPQ;TFE3"),
(189, "", "head-neck squamous cell", "Somatic", "MET"),
(190, "", "CNS tumours", "Somatic", "MLH1"),
(191, "CNS", "central nervous system", "Germline", "MLH1"),
(192, "", "T cell prolymphocytic leukaemia", "Somatic", "MTCP1"),
(193, "", "adenoid cystic carcinoma", "Somatic", "MYB;NFIB;SPEN"),
(194, "", "amplified in other cancers", "Somatic", "MYC"),
(195, "", "small cell lung carcinoma", "Somatic, Germline", "MYCL;RB1;RB1"),
(196, "", "ABC-DLBCL", "Somatic", "MYD88"),
(197, "", "solitary fibrous tumour", "Somatic", "NAB2;STAT6"),
(198, "", "meningeal haemangiopericytoma", "Somatic", "NAB2;STAT6"),
(199, "", "neurofibroma", "Somatic, Germline", "NF1;NF1"),
(200, "", "acoustic neuroma", "Somatic, Germline", "NF2;NF2"),
(201, "HNSCC", "head and neck squamous cell carcinoma", "Somatic", "NFE2L2;TSC2"),
(202, "", "skin SCC", "Somatic", "NOTCH1"),
(203, "", "lung SCC", "Somatic", "NOTCH1"),
(204, "", "head and neck SCC", "Somatic", "NOTCH1"),
(205, "", "marginal zone lymphoma", "Somatic", "NOTCH2"),
(206, "APL", "acute promyelocytic leukaemia", "Somatic", "NPM1;NUMA1;PML;RARA;STAT5B;TRIM24;ZBTB16"),
(207, "", "relapse ALL", "Somatic", "NT5C2"),
(208, "", "lethal midline carcinoma", "Somatic", "NUTM1"),
(209, "", "endometrial stromal sarcoma", "Somatic", "NUTM2A;NUTM2B;YWHAE"),
(210, "", "Down syndrome associated ALL", "Somatic", "P2RY8;P2RY8"),
(211, "", "AML ", "Germline", "PALB2"),
(212, "", "follicular thyroid", "Somatic", "PAX8;PPARG"),
(213, "", "pre B-ALL", "Somatic", "PBX1;TCF3"),
(214, "", "lipoblastoma", "Somatic", "PLAG1"),
(215, "", "skin cancer", "Somatic", "POLE"),
(216, "", "colorectal cancer susceptibility", "Germline", "POLE"),
(217, "", "various leukaemia", "Germline", "PRF1"),
(218, "", "myxoma", "Germline", "PRKAR1A"),
(219, "", "endocrine", "Germline", "PRKAR1A"),
(220, "", "harmartoma", "Germline", "PTEN"),
(221, "", "carcinoma", "Somatic", "RAC1"),
(222, "", "endometrium", "Somatic", "RAD21"),
(223, "", "skin sqamous cell", "Germline", "RECQL4"),
(224, "", "medullary thyroid", "Somatic, Germline", "RET;RET"),
(225, "", " papillary thyroid", "Germline", "RET"),
(226, "", "diffuse gastric", "Somatic", "RHOA"),
(227, "", "T cell lymphomas", "Somatic", "RHOA"),
(228, "", "paediatric Burkitt lymphoma", "Somatic", "RHOA"),
(229, "", "ovary", "Somatic", "RNF43"),
(230, "", "pancreas", "Somatic", "RNF43"),
(231, "", "preB- ALL", "Somatic", "RUNX1"),
(232, "", "paraganglioma", "Germline", "SDHAF2;SDHB;SDHC;SDHD"),
(233, "sAML", "secondary acute myeloid leukaemia", "Somatic", "SETBP1;SH2B3"),
(234, "", "MDS/MPN-U", "Somatic", "SETBP1"),
(235, "", "neuroepithelial tumours", "Germline", "SETBP1"),
(236, "", "myelodysplastic syndrome", "Somatic", "SF3B1"),
(237, "", "erythrocytosis", "Somatic", "SH2B3"),
(238, "", "small intestine", "Somatic", "SMAD4"),
(239, "", "gastrointestinal polyp", "Germline", "SMAD4"),
(240, "SCCOHT", "small cell carcinoma of the ovary, hypercalcaemic type", "Somatic", "SMARCA4"),
(241, "", "malignant rhabdoid", "Somatic, Germline", "SMARCB1;SMARCB1"),
(242, "", "oesophageal squamous carcinoma", "Somatic", "SOX2"),
(243, "", "serous endometrial", "Somatic", "SPOP"),
(244, "", "follicular lymphoma", "Somatic", "SRSF3;TNFRSF14"),
(245, "", "synovial sarcoma", "Somatic", "SS18;SS18L1;SSX1;SSX2;SSX4"),
(246, "", "bladder carcinoma", "Somatic", "STAG2;TSC1"),
(247, "", "Ewing's sarcoma", "Somatic", "STAG2"),
(248, "", "myeloid neoplasms", "Somatic", "STAG2"),
(249, "", "T-cell large granular lymphocytic leukaemia", "Somatic", "STAT3"),
(250, "", "paediatric large granular lymphocytic leukaemia", "Germline", "STAT3"),
(251, "", "large granular lymphocytic leukaemia", "Somatic", "STAT5B"),
(252, "", "jejunal hamartoma", "Germline", "STK11"),
(253, "", "testicular", "Germline", "STK11"),
(254, "", "anaplastic thyroid", "Somatic", "STRN"),
(255, "", "lymphoblastic leukaemia/biphasic", "Somatic", "TAL1"),
(256, "", "splenic marginal zone lymphoma", "Somatic", "TBL1XR1"),
(257, "", "primary central nervous system lymphoma", "Somatic", "TBL1XR1"),
(258, "", "gallbladder carcinoma", "Somatic", "TBL1XR1"),
(259, "T-CLL", "T-cell chronic lymphocytic leukaemia", "Somatic", "TCL1A"),
(260, "pre-B ALL", "pre-B-cell acute lymphoblastic leukaemia", "Somatic", "TFPT"),
(261, "", "marginal zone B-cell lymphomas", "Somatic", "TNFAIP3"),
(262, "", "adrenocortical", "Somatic", "TP53"),
(263, "", "adrenocortical carcinoma", "Germline", "TP53"),
(264, "", "T-cell leukaemia", "Somatic", "TRD"),
(265, "", "renal cell carcinoma", "Somatic, Germline", "TSC1;TSC1;TSC2"),
(266, "", "hamartoma", "Germline", "TSC1;TSC2"),
(267, "", "tuberous sclerosis tuber", "Germline", "TSC1;TSC2"),
(268, "", "pulmonary lymphangioleiomyomatosis (LAM)", "Somatic", "TSC2"),
(269, "", "renal angiomyolipoma", "Somatic", "TSC2"),
(270, "", "toxic thyroid adenoma", "Somatic", "TSHR"),
(271, "", "thyroid adenoma", "Germline", "TSHR"),
(272, "", "mantle cell lymphoma", "Somatic", "UBR5"),
(273, "", "haemangioma", "Somatic, Germline", "VHL;VHL"),
(274, "", "desmoplastic small round cell tumour", "Somatic", "WT1"),
(275, "", "follicular thyroid adenoma", "Somatic", "ZNF331");
